version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gmap_postgres
    restart: always
    environment:
      POSTGRES_USER: gmap
      POSTGRES_PASSWORD: gmap
      POSTGRES_DB: gmap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: